// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnzgutpqayyhwuqkcnbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRuemd1dHBxYXl5aHd1cWtjbmJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MzE3MDksImV4cCI6MjA2NjMwNzcwOX0.3EMb6IDjJX32JNsZ1ez461dLZ_DPmziaP8Dbb1IUlts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);